{{- if and .Values.service.enabled .Values.deployment.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hp-app.fullname" . }}
  labels:
    {{- include "hp-app.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity | default "None" }}
  selector:
    {{- include "hp-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
{{- end }}
